"""initial migration

Revision ID: 577a7dc1dfc5
Revises: 
Create Date: 2026-05-10 18:01:50.834697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577a7dc1dfc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vote', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Vote_UserID_ReportID_key'), type_='unique')
        batch_op.create_unique_constraint('unique_user_vote', ['UserID', 'ReportID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vote', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_vote', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('Vote_UserID_ReportID_key'), ['UserID', 'ReportID'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
