"""AuditLog Updated

Revision ID: 8423ff463676
Revises: f843bd8b84e3
Create Date: 2026-05-11 23:11:43.789499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8423ff463676'
down_revision = 'f843bd8b84e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuditLog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ReportID', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('OldStatus', postgresql.ENUM('Reported', 'Inspected', 'In Progress', 'Resolved', name='report_status'), nullable=True))
        batch_op.add_column(sa.Column('NewStatus', postgresql.ENUM('Reported', 'Inspected', 'In Progress', 'Resolved', name='report_status'), nullable=True))
        batch_op.create_foreign_key(None, 'Report', ['ReportID'], ['ReportID'])
        batch_op.drop_column('ActionPerformed')
        batch_op.drop_column('TargetReportID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuditLog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TargetReportID', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ActionPerformed', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('NewStatus')
        batch_op.drop_column('OldStatus')
        batch_op.drop_column('ReportID')

    # ### end Alembic commands ###
