"""Abdullah ka db daaldiya

Revision ID: bc1adb54e9ed
Revises: e73be84b2cdf
Create Date: 2026-05-12 23:40:33.688773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc1adb54e9ed'
down_revision = 'e73be84b2cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AdminActionLog')
    op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('Report', schema=None) as batch_op:
        batch_op.alter_column('SubmitterID',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('ImageURL',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('Category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('Location',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('Latitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True,
               comment=None,
               existing_comment='PostGIS spatial compatible')
        batch_op.alter_column('Longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True,
               comment=None,
               existing_comment='PostGIS spatial compatible')
        batch_op.alter_column('Status',
               existing_type=postgresql.ENUM('Reported', 'Inspected', 'InProgress', 'Resolved', name='report_status'),
               nullable=True,
               existing_server_default=sa.text("'Reported'::report_status"))
        batch_op.alter_column('ExpectedTimeOfArrival',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Nullable',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_report_spatial_geography'), postgresql_using='gist')
        batch_op.drop_constraint(batch_op.f('Report_SubmitterID_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['SubmitterID'], ['UserID'])

    with op.batch_alter_table('ReportAuditLog', schema=None) as batch_op:
        batch_op.alter_column('AdminID',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='The admin updating the report')
        batch_op.alter_column('ReportID',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('OldStatus',
               existing_type=postgresql.ENUM('Reported', 'Inspected', 'InProgress', 'Resolved', name='report_status'),
               comment=None,
               existing_comment='What the status was before',
               existing_nullable=True)
        batch_op.alter_column('NewStatus',
               existing_type=postgresql.ENUM('Reported', 'Inspected', 'InProgress', 'Resolved', name='report_status'),
               nullable=True,
               comment=None,
               existing_comment='What the status was changed to')
        batch_op.drop_constraint(batch_op.f('ReportAuditLog_AdminID_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ReportAuditLog_ReportID_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Report', ['ReportID'], ['ReportID'])
        batch_op.create_foreign_key(None, 'User', ['AdminID'], ['UserID'])

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('Email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('PasswordHash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('Role',
               existing_type=postgresql.ENUM('Citizen', 'Admin', 'SuperAdmin', name='user_role'),
               nullable=True,
               existing_server_default=sa.text("'Citizen'::user_role"))
        batch_op.alter_column('AssignedRegion',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nullable, only for Admins',
               existing_nullable=True)
        batch_op.alter_column('CNIC',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('PhoneNumber',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('User_Email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('User_PhoneNumber_key'), type_='unique')
        batch_op.drop_column('DepartmentID')

    with op.batch_alter_table('Vote', schema=None) as batch_op:
        batch_op.alter_column('UserID',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('ReportID',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_index(batch_op.f('Vote_UserID_ReportID_idx'))
        batch_op.create_unique_constraint('unique_user_vote', ['UserID', 'ReportID'])
        batch_op.drop_constraint(batch_op.f('Vote_UserID_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('Vote_ReportID_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['UserID'], ['UserID'])
        batch_op.create_foreign_key(None, 'Report', ['ReportID'], ['ReportID'])
        batch_op.drop_table_comment(
        existing_comment='Junction table to prevent duplicate voting (Many-to-Many)'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vote', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Junction table to prevent duplicate voting (Many-to-Many)',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Vote_ReportID_fkey'), 'Report', ['ReportID'], ['ReportID'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('Vote_UserID_fkey'), 'User', ['UserID'], ['UserID'], deferrable=True)
        batch_op.drop_constraint('unique_user_vote', type_='unique')
        batch_op.create_index(batch_op.f('Vote_UserID_ReportID_idx'), ['UserID', 'ReportID'], unique=True)
        batch_op.alter_column('ReportID',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('UserID',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DepartmentID', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Nullable, only for Admins'))
        batch_op.create_unique_constraint(batch_op.f('User_PhoneNumber_key'), ['PhoneNumber'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('User_Email_key'), ['Email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('PhoneNumber',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('CNIC',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('AssignedRegion',
               existing_type=sa.VARCHAR(length=100),
               comment='Nullable, only for Admins',
               existing_nullable=True)
        batch_op.alter_column('Role',
               existing_type=postgresql.ENUM('Citizen', 'Admin', 'SuperAdmin', name='user_role'),
               nullable=False,
               existing_server_default=sa.text("'Citizen'::user_role"))
        batch_op.alter_column('PasswordHash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('Email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('Name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('ReportAuditLog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ReportAuditLog_ReportID_fkey'), 'Report', ['ReportID'], ['ReportID'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('ReportAuditLog_AdminID_fkey'), 'User', ['AdminID'], ['UserID'], deferrable=True)
        batch_op.alter_column('NewStatus',
               existing_type=postgresql.ENUM('Reported', 'Inspected', 'InProgress', 'Resolved', name='report_status'),
               nullable=False,
               comment='What the status was changed to')
        batch_op.alter_column('OldStatus',
               existing_type=postgresql.ENUM('Reported', 'Inspected', 'InProgress', 'Resolved', name='report_status'),
               comment='What the status was before',
               existing_nullable=True)
        batch_op.alter_column('ReportID',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('AdminID',
               existing_type=sa.UUID(),
               nullable=False,
               comment='The admin updating the report')

    with op.batch_alter_table('Report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Report_SubmitterID_fkey'), 'User', ['SubmitterID'], ['UserID'], deferrable=True)
        batch_op.create_index(batch_op.f('idx_report_spatial_geography'), [sa.literal_column('(st_makepoint("Longitude"::double precision, "Latitude"::double precision)::geography)')], unique=False, postgresql_using='gist')
        batch_op.alter_column('ExpectedTimeOfArrival',
               existing_type=postgresql.TIMESTAMP(),
               comment='Nullable',
               existing_nullable=True)
        batch_op.alter_column('Status',
               existing_type=postgresql.ENUM('Reported', 'Inspected', 'InProgress', 'Resolved', name='report_status'),
               nullable=False,
               existing_server_default=sa.text("'Reported'::report_status"))
        batch_op.alter_column('Longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False,
               comment='PostGIS spatial compatible')
        batch_op.alter_column('Latitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False,
               comment='PostGIS spatial compatible')
        batch_op.alter_column('Location',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('Category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('ImageURL',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('SubmitterID',
               existing_type=sa.UUID(),
               nullable=False)

    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('AdminActionLog',
    sa.Column('LogID', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('SuperAdminID', sa.UUID(), autoincrement=False, nullable=False, comment='The person performing the action'),
    sa.Column('TargetAdminID', sa.UUID(), autoincrement=False, nullable=False, comment='The account being modified'),
    sa.Column('Action', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment="e.g., 'Created Account', 'Revoked Access'"),
    sa.Column('Timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['SuperAdminID'], ['User.UserID'], name=op.f('AdminActionLog_SuperAdminID_fkey'), deferrable=True),
    sa.PrimaryKeyConstraint('LogID', name=op.f('AdminActionLog_pkey'))
    )
    # ### end Alembic commands ###
