"""Table modified

Revision ID: e73be84b2cdf
Revises: 39a487ac0acf
Create Date: 2026-05-11 23:35:04.307049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73be84b2cdf'
down_revision = '39a487ac0acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('User_Email_key1'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('User_Email_key1'), ['Email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
