"""Phone Number added

Revision ID: f843bd8b84e3
Revises: 577a7dc1dfc5
Create Date: 2026-05-10 20:36:13.479061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f843bd8b84e3'
down_revision = '577a7dc1dfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PhoneNumber', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['Email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('PhoneNumber')

    # ### end Alembic commands ###
